name: CI Master
on:
  push:
    branches: [master, main]

permissions:
  contents: read

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6, 7]

    permissions:
      contents: write
      packages: write # allow GITHUB_TOKEN to publish packages
      pull-requests: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Start Redis
        uses: supercharge/redis-github-action@ea9b21c6ecece47bd99595c532e481390ea0f044 # 1.8.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: npm install
      - run: npm run check
      - run: npm run test

      - uses: nickcharlton/diff-check@9fa7ac2bd275b9ec60f13dbcef1b90cfaadc1872 # main
        if: ${{ matrix.redis-version == '7' }}
        with:
          command: npm run build
          message: "Please make sure to run 'npm run fix && npm run build' before committing."

      - name: Run release-please
        id: release_please
        if: ${{ matrix.redis-version == '7' }}
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3
        id: publish
        if: ${{ matrix.redis-version == '7' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: ${{ steps.publish.outputs.type && matrix.redis-version == '7' }}
        run: echo "Version changed!"
